spring:
  application:
    name: coincome
  datasource:
    url: jdbc:mysql://localhost:3307/bitcome?useSSL=false&allowLoadLocalInfile=true&connectionTimeZone=America/New_York&forceConnectionTimeZoneToSession=true
    username: agou
    password: Aa121543912gzq!
  jackson:
    time-zone: America/New_York
  mvc:
    time-zone: America/New_York

server:
  forward-headers-strategy: framework
  port: 8080


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

coincome:
  file:
    upload-dir: coincome/uploads

# MyBatis-Plus 配置
mybatis-plus:
  # 如果你有自定义 XML（比如某些复杂查询），放在 resources/mapper 里
  mapper-locations: classpath*:mapper/*.xml
  # 实体类包路径（User、Asset、TransactionRecord 等）
  type-aliases-package: com.nyu.coincome.entity
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印 SQL

  global-config:
    db-config:
      id-type: auto           # 主键用数据库 AUTO_INCREMENT
      table-underline: true   # 表字段下划线风格
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.nyu.coincome.mapper: debug   # 打印 Mapper 的 SQL
    com.baomidou.mybatisplus: debug



